name: Vercel Deployment
on:
  push:
    branches:
      - main
      - release/*
      - feature/*
      - bugfix/*

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scan-step:
          - SonarCloud Scan
          - OWASP Dependency-Check
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ${{ matrix.scan-step }}
        if: matrix.scan-step == 'SonarCloud Scan'
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
      - name: ${{ matrix.scan-step }}
        if: matrix.scan-step == 'OWASP Dependency-Check'
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'ALL'
          args: >
            --failOnCVSS 4
            --enableRetired

      - name: Upload OWASP Dependency-Check results
        if: always() && matrix.scan-step == 'OWASP Dependency-Check'
        uses: actions/upload-artifact@v3
        with:
          name: Depcheck report
          path: ${{github.workspace}}/reports
          
  build_and_deploy:
    name: Build and deploy
    needs: testing
    if: |
      always() &&
      !contains(needs.testing.result, 'failure') &&
      !contains(needs.testing.result, 'cancelled')
    runs-on: ubuntu-latest
    steps:
      - name: Set BUILD_TYPE environment variable
        run: echo "BUILD_TYPE=$(if [[ $GITHUB_REF == 'refs/heads/main' || $GITHUB_REF == refs/heads/release/* || $GITHUB_REF == refs/heads/bugfix/* ]]; then echo 'production'; else echo 'preview'; fi)" >> $GITHUB_ENV
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{ env.BUILD_TYPE }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build ${{ env.BUILD_TYPE == 'production' && '--prod' }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt ${{ env.BUILD_TYPE == 'production' && '--prod' || '' }} --token=${{ secrets.VERCEL_TOKEN }}