name: Vercel Deployment

on:
  push:
    branches:
      - main
      - release/*
      - feature/*
      - bugfix/*

jobs:
  sonarcloud:
    uses: ./.github/workflows/sonarcloud.yml
    secrets:
      git_token: ${{ secrets.GITHUB_TOKEN }}
      sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
  build_and_deploy:
    uses: ./.github/workflows/build_and_deploy.yml