name: Vercel Deployment

on:
  push:
    branches:
      - main
      - release/*
      - feature/*
      - bugfix/*

jobs:
  sonarcloud:
    uses: ./.github/workflows/jobs/sonarcloud.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  eslint:
    uses: ./.github/workflows/jobs/eslint.yml
  owasp:
    uses: ./.github/workflows/jobs/owasp.yml
  build_and_deploy:
    uses: ./.github/workflows/jobs/build_and_deploy.yml
    needs: ['sonarcloud', 'eslint', 'owasp']