name: Vercel Deployment

on:
  push:
    branches:
      - main
      - release/*
      - feature/*
      - bugfix/*

jobs:
  sonarcloud:
    uses: ./.github/workflows/sonarcloud.yml
  eslint:
    uses: ./.github/workflows/eslint.yml
  owasp:
    uses: ./.github/workflows/owasp.yml
  build_and_deploy:
    uses: ./.github/workflows/build_and_deploy.yml
    needs: ['sonarcloud', 'eslint', 'owasp']